"""Page 1 · Site ranking: where should the next store open? (Features 1 and 6, US1)"""

import pandas as pd
import streamlit as st

from sitesense import charts, local_llm, queries, scoring
from sitesense.components.notices import PROXY, page_header
from sitesense.components.sidebar import current_filters


def current_weights() -> dict[str, float]:
    """Weights chosen on this page, shared with the comparison page."""
    stored = st.session_state.get("weights", scoring.DEFAULT_WEIGHTS)
    return {key: float(value) for key, value in stored.items()}


def ranked_areas(metro: str, categories: tuple[str, ...]) -> pd.DataFrame:
    factors = queries.area_factors(metro, categories)
    scored = scoring.score_areas(factors, current_weights())
    table = scored.merge(queries.areas(metro), on="area_id")
    table["heavy_rain_pct"] = (table.weather_resilience - 1) * 100
    table["sensitivity"] = table.heavy_rain_pct.map(scoring.sensitivity_label)
    return table


def _weights_panel() -> None:
    stored = current_weights()
    with st.expander("Scoring weights", expanded=True):
        columns = st.columns(len(scoring.FACTORS))
        weights = {
            factor.key: column.slider(
                factor.label, 0, 100, int(stored[factor.key]), step=5, key=f"w_{factor.key}"
            )
            for factor, column in zip(scoring.FACTORS, columns, strict=True)
        }
        st.session_state["weights"] = weights
        shares = scoring.normalise_weights(weights)
        st.caption(
            "Weights are rescaled to 100%: "
            + " · ".join(f"{f.label} {shares[f.key]:.0%}" for f in scoring.FACTORS)
        )


def _map(table: pd.DataFrame) -> None:
    colors = [charts.SEQUENTIAL(score / 100) for score in table.score]
    points = table.assign(
        radius=120 + table.avg_weekly_checkins * 6,
        color=[f"#{int(r * 255):02x}{int(g * 255):02x}{int(b * 255):02x}" for r, g, b, _ in colors],
    )
    st.map(points, latitude="centroid_lat", longitude="centroid_lon", size="radius", color="color")
    st.caption("Circle size = check-ins per week · darker = higher score")


def _ranking_table(table: pd.DataFrame) -> None:
    view = pd.DataFrame(
        {
            "#": table["rank"],
            "Area": table.name + " · " + table.area_id,
            "Score": table.score.round(0),
            "Check-ins / wk": table.avg_weekly_checkins.round(0),
            "Share trend": table.growth_yoy * 100,
            "Rating": table.avg_stars,
            "Competitors": table.competitor_count,
            "Weather sensitivity": table.sensitivity,
        }
    )
    st.dataframe(
        view,
        hide_index=True,
        width="stretch",
        column_config={
            "Score": st.column_config.ProgressColumn(min_value=0, max_value=100, format="%d"),
            "Check-ins / wk": st.column_config.NumberColumn(format="%d"),
            "Share trend": st.column_config.NumberColumn(
                format="%+.0f%%",
                help="Change in the area's share of metro check-ins, 2019 vs 2018 "
                "(before COVID-19). Shares, not raw counts, because Yelp use changes yearly.",
            ),
            "Rating": st.column_config.NumberColumn(format="%.1f ★"),
        },
    )
    st.download_button(
        "Download ranking (CSV)",
        view.to_csv(index=False),
        file_name="sitesense_ranking.csv",
        mime="text/csv",
    )


def _explanation(table: pd.DataFrame, factors: pd.DataFrame) -> None:
    labels = {
        str(row.area_id): f"#{row.rank} {row.name} ({row.area_id})" for row in table.itertuples()
    }
    area_id = st.selectbox("Explain area", list(labels), format_func=labels.__getitem__)
    row = table[table.area_id == area_id].iloc[0]
    weights = current_weights()
    contribution = scoring.contributions(factors, area_id, weights)
    st.subheader(f"Why {row['name']} ranks #{row['rank']}")
    left, right = st.columns(2)
    score = float(row["score"])
    left.metric("Score", f"{score:.0f}/100")
    right.metric("Baseline (metro avg)", f"{scoring.baseline_score(factors, weights):.0f}")
    st.pyplot(charts.contribution_bars(contribution))
    sentence = scoring.explain_area(str(row["name"]), score, int(row["rank"]), contribution)
    with st.container(border=True):
        st.caption("IN PLAIN WORDS")
        st.write(sentence)
    if st.button("Write a longer explanation with the local AI (Ollama, optional)"):
        details = "\n".join(
            f"- {label}: {points:+.1f}"
            for label, points in zip(contribution.label, contribution.points, strict=True)
        )
        try:
            with st.spinner("Asking the local model…"):
                st.write(local_llm.generate(local_llm.ranking_prompt(sentence, details)))
            st.caption("Generated by a local language model from the numbers above.")
        except local_llm.LocalModelUnavailable as error:
            st.info(f"{error} The template explanation above is unchanged.")


def render() -> None:
    filters = current_filters()
    page_header(
        "Where should the next store open?",
        "Candidate areas (ZIP codes) ranked by Yelp check-in demand, growth, ratings, "
        "competition and weather resilience.",
        PROXY,
    )
    areas = queries.areas(filters.metro)
    factors = queries.area_factors(filters.metro, filters.categories)
    activity = queries.activity_hourly(filters.metro, filters.categories)
    in_range = activity[
        (activity.obs_date >= pd.Timestamp(filters.start))
        & (activity.obs_date <= pd.Timestamp(filters.end))
    ]
    matched = areas.business_count[areas.weather_cell_id.notna()].sum()
    years = (filters.end - filters.start).days / 365.25

    columns = st.columns(4)
    columns[0].metric("Candidate areas", len(factors), help="ZIP codes with ≥ 5 businesses")
    columns[1].metric("Businesses in scope", f"{areas.business_count.sum():,}")
    columns[2].metric(
        "Check-ins analysed", f"{in_range.checkins.sum():,}", f"{years:.0f} years of history",
        delta_color="off",
    )  # fmt: skip
    columns[3].metric(
        "Weather match rate", f"{matched / areas.business_count.sum():.0%}", "target ≥ 95%",
        delta_color="off",
    )  # fmt: skip

    _weights_panel()
    table = ranked_areas(filters.metro, filters.categories)
    left, right = st.columns([3, 2], gap="large")
    with left:
        st.subheader("Candidate map")
        _map(table)
        st.subheader("Ranking")
        _ranking_table(table)
    with right, st.container(border=True):
        _explanation(table, factors)
